os: linux
dist: bionic
language: php
php:
    - 8.0.0
env:
    global:
        - XDEBUG_MODE=coverage

install:
    # ensure that the Composer config is valid
    - composer validate

    # install Composer packages, will also trigger dump-autoload
    - travis_retry composer install --no-interaction --no-suggest

script:
    - composer test -- --coverage-clover=coverage.xml
    - ls -al

after_success:
    - bash <(curl -s https://codecov.io/bash) -f coverage.xml
cache:
    directories:
        - vendor
        - ~/.composer/cache
        - ~/pecl_cache
jobs:
    fast_finish: true
